// Data mini game "Tebak dari Petunjuk": petunjuk (c) diurutkan dari yang paling sulit ke yang paling mudah; tidak boleh menyebut jawabannya.
// Pilihan jawaban diambil dari jawaban lain di set yang sama, jadi setiap set minimal 6 jawaban. Isi dari PPT kisi-kisi BKN 2025 (hal. per set).
window.TEBAK = [
  { id: "t-presiden", topic: "sejarah", title: "Tebak presidennya", pages: "21, 59-67", ask: "Siapa presiden yang dimaksud?", items: [
    { a: "Soekarno", c: ["Menjabat 21 tahun 7 bulan", "Pertama kali menyampaikan istilah Pancasila di sidang BPUPKI", "Presiden pertama, 1945-1967"] },
    { a: "Soeharto", c: ["Kabinet Pembangunan I sampai VII", "Menjabat 31 tahun 2 bulan", "Mundur pada 21 Mei 1998"] },
    { a: "B.J. Habibie", c: ["Kabinetnya berisi unsur ABRI, Golkar, PPP, dan PDI", "Menerbitkan UU 40/1999 tentang Pers", "Referendum Timor Timur", "Kabinet Reformasi Pembangunan"] },
    { a: "Abdurrahman Wahid", c: ["Menggelar dialog kebangsaan pemberantasan korupsi dan dialog dengan Aceh", "Memberi hak setara bagi penganut Konghucu", "Mencabut aturan yang menghalangi perayaan Imlek", "Kabinet Persatuan Nasional"] },
    { a: "Megawati Soekarnoputri", c: ["Membentuk kabinet untuk menghapus KKN dan keluar dari krisis", "Menjabat 3 tahun 3 bulan", "Pemilihan presiden langsung mulai diterapkan pada pemilu 2004", "Kabinet Gotong Royong"] },
    { a: "Susilo Bambang Yudhoyono", c: ["Kasus Bank Century dan mega proyek Hambalang", "UU 24/2011: PT Askes menjadi BPJS Kesehatan", "Melunasi utang IMF dan masuk G-20", "Kabinet Indonesia Bersatu"] },
    { a: "Joko Widodo", c: ["Mendorong transformasi digital layanan pemerintahan", "Meluncurkan KIS, KIP, dan bansos", "Menghadapi pandemi COVID-19", "Kabinet Kerja dan Kabinet Indonesia Maju"] },
    { a: "Prabowo Subianto", c: ["Hadir di Shangri-La Dialogue, KTT APEC, dan KTT G20", "Program Makan Siang Gratis", "Kabinet dengan 48 kementerian", "Kabinet Merah Putih"] }] },
  { id: "t-pasal", topic: "uud", title: "Tebak pasalnya", pages: "47-55", ask: "Pasal berapa yang dimaksud?", items: [
    { a: "Pasal 1", c: ["Kedaulatan berada di tangan rakyat dan dilaksanakan menurut UUD", "Indonesia adalah negara hukum", "Negara kesatuan yang berbentuk republik"] },
    { a: "Pasal 2", c: ["Segala putusan ditetapkan dengan suara terbanyak", "Bersidang sedikitnya sekali dalam lima tahun di ibu kota", "MPR terdiri atas anggota DPR dan anggota DPD"] },
    { a: "Pasal 3", c: ["Hanya dapat memberhentikan Presiden dalam masa jabatannya menurut UUD", "Melantik Presiden dan/atau Wakil Presiden", "MPR berwenang mengubah dan menetapkan UUD"] },
    { a: "Pasal 4", c: ["Dalam melakukan kewajibannya dibantu satu orang Wakil Presiden", "Presiden memegang kekuasaan pemerintahan menurut UUD"] },
    { a: "Pasal 5", c: ["Presiden menetapkan peraturan pemerintah untuk menjalankan undang-undang", "Presiden berhak mengajukan RUU kepada DPR"] },
    { a: "Pasal 6", c: ["Tidak pernah mengkhianati negara, mampu secara rohani dan jasmani", "WNI sejak kelahirannya", "Syarat calon Presiden dan Wakil Presiden"] },
    { a: "Pasal 6A", c: ["Lebih dari 50% suara dan sedikitnya 20% di lebih dari setengah jumlah provinsi", "Diusulkan partai politik atau gabungan partai politik", "Presiden dan Wakil Presiden dipilih langsung dalam satu pasangan"] },
    { a: "Pasal 7", c: ["Dapat dipilih kembali hanya untuk satu kali masa jabatan", "Presiden dan Wakil Presiden memegang jabatan selama lima tahun"] },
    { a: "Pasal 7A", c: ["Pengkhianatan, korupsi, penyuapan, pidana berat, perbuatan tercela", "Presiden dapat diberhentikan MPR atas usul DPR"] },
    { a: "Pasal 7B", c: ["Pendapat DPR ini bagian dari fungsi pengawasan", "DPR harus lebih dulu meminta MK memeriksa, mengadili, dan memutus"] }] },
  { id: "t-pancasila", topic: "pancasila", title: "Tebak istilah Pancasila", pages: "21-33", ask: "Istilah atau tokoh apa yang dimaksud?", items: [
    { a: "Mpu Tantular", c: ["Kitabnya menyebut Pancasila berbatu sendi yang lima", "Pancasila = pelaksanaan kesusilaan yang lima", "Pengarang kitab Sutasoma"] },
    { a: "Muhammad Yamin", c: ["Sila = sendi, asas, dasar, atau peraturan tingkah laku yang baik", "Pancasila = lima dasar berisi pedoman tingkah laku yang baik dan penting"] },
    { a: "Notonegoro", c: ["Diharapkan menjadi pandangan hidup dan pemersatu bangsa", "Pancasila = dasar falsafah dan ideologi negara"] },
    { a: "PPKI", c: ["Terdiri dari wakil-wakil rakyat", "Asal sebutan Pancasila sebagai perjanjian luhur", "Mengesahkan Pancasila dan UUD 1945 pada 18 Agustus 1945"] },
    { a: "Volksgeist", c: ["Agar Indonesia tetap hidup dalam jiwa Pancasila", "Sebutan untuk jiwa atau nyawa setiap bangsa"] },
    { a: "Sumber segala sumber hukum", c: ["Sila-sila = nilai dasar, penjabarannya = nilai instrumental", "Tidak boleh ada peraturan yang bertentangan dengan Pancasila"] },
    { a: "Kepribadian bangsa", c: ["Diwujudkan lewat tingkah laku dan sikap mental", "Corak khas yang membedakan bangsa Indonesia dari bangsa lain"] },
    { a: "Bahasa Sanskerta", c: ["Terkait kasta Brahmana", "Asal kata panca = lima dan sila = dasar"] }] },
  { id: "t-kepegawaian", topic: "kepegawaian", title: "Tebak istilah kepegawaian", pages: "107-121", ask: "Istilah apa yang dimaksud?", items: [
    { a: "PNS", c: ["Diangkat oleh pejabat pembina kepegawaian", "Untuk menduduki jabatan pemerintahan", "Diangkat sebagai pegawai ASN secara tetap"] },
    { a: "PPPK", c: ["Melaksanakan tugas pemerintahan", "Untuk jangka waktu tertentu", "Diangkat berdasarkan perjanjian kerja"] },
    { a: "BerAKHLAK", c: ["Dijabarkan dalam kode etik dan kode perilaku ASN", "Tujuh nilai, dari berorientasi pelayanan sampai kolaboratif", "Nilai dasar ASN"] },
    { a: "Cuti tahunan", c: ["Diajukan tertulis kepada PPK", "12 hari"] },
    { a: "Cuti besar", c: ["Dipakai untuk melahirkan anak keempat dan seterusnya", "Syarat sudah bekerja 5 tahun", "Paling lama 3 bulan"] },
    { a: "CLTN", c: ["Syarat sudah bekerja 5 tahun", "Paling lama 3 tahun", "Cuti di luar tanggungan negara"] },
    { a: "Cuti sakit", c: ["Bisa ditambah 6 bulan dengan keterangan tim penguji kesehatan", "Maksimal 1 tahun", "Memakai surat dokter"] },
    { a: "Hukuman disiplin sedang", c: ["Selama 6, 9, atau 12 bulan", "Pemotongan tunjangan kinerja 25%"] },
    { a: "Bhinneka Karya Abdi Negara", c: ["Doktrin korps pegawai", "Tugas beraneka ragam, tetap bersatu dalam pengabdian"] },
    { a: "Panca Prasetya KORPRI", c: ["Diawali: Kami anggota Korps Pegawai Republik Indonesia...", "Lima janji anggota korps pegawai"] }] },
  { id: "t-tkt", topic: "gg", title: "Tebak istilah pelayanan dan kebijakan", pages: "122-149", ask: "Istilah atau pihak apa yang dimaksud?", items: [
    { a: "Ombudsman", c: ["Bagian dari organisasi penyelenggara pelayanan publik", "Pengawas penyelenggaraan pelayanan publik"] },
    { a: "Menteri PANRB", c: ["Pejabat di bidang pendayagunaan aparatur negara", "Perumus kebijakan nasional pelayanan publik"] },
    { a: "UU 25/2009", c: ["Memuat 12 asas pelayanan", "Undang-undang tentang Pelayanan Publik"] },
    { a: "Transparansi", c: ["Informasi harus dapat dipahami dan dimonitor", "Dibangun atas dasar kebebasan arus informasi"] },
    { a: "Kepastian hukum", c: ["Terutama untuk hak asasi manusia", "Kerangka aturan harus adil dan dilaksanakan tanpa pandang bulu", "Rule of law"] },
    { a: "Formulasi kebijakan", c: ["Tahap kedua siklus kebijakan", "Mendefinisikan masalah dan mendaftar alternatif solusi"] },
    { a: "Kebijakan meso", c: ["Bersifat penjelas pelaksanaan", "Contohnya Peraturan Menteri dan SKB antarmenteri"] },
    { a: "Perpres 81/2010", c: ["Memuat prinsip dasar good governance, tujuan RB, dan sasaran RB", "Grand Design Reformasi Birokrasi"] }] },
  { id: "t-renstra", topic: "renstra", title: "Tebak dokumen dan istilah perencanaan", pages: "92-105", ask: "Dokumen atau istilah apa yang dimaksud?", items: [
    { a: "RPJP Nasional", c: ["Dijabarkan ke dalam RPJM Nasional", "Berjangka 20 tahun"] },
    { a: "RPJM Nasional", c: ["Menjadi pedoman Renstra K/L", "Berjangka 5 tahun"] },
    { a: "RKP", c: ["Menjadi dasar APBN yang dibahas bersama DPR", "Rencana kerja pemerintah berjangka 1 tahun"] },
    { a: "Renja K/L", c: ["Berjangka 1 tahun", "Penjabaran Renstra K/L"] },
    { a: "Asta Cita", c: ["Bagian dari arah pembangunan bersama visi misi Presiden dan RPJPN", "Sama dengan 8 Prioritas Nasional"] },
    { a: "FEW Nexus", c: ["Pendekatan swasembada dalam PN 2", "Pangan, energi, dan air"] },
    { a: "Triple Planetary Crisis", c: ["Isu pada sasaran ekonomi hijau PN 2", "Perubahan iklim, polusi, dan hilangnya keanekaragaman hayati"] },
    { a: "Program hasil terbaik cepat", c: ["Antara lain Badan Penerimaan Negara dan kenaikan gaji ASN", "Delapan program, nomor satu makan siang dan susu gratis"] }] },
  { id: "t-bindo", topic: "bindo", title: "Tebak istilah bahasa Indonesia", pages: "84-90", ask: "Istilah apa yang dimaksud?", items: [
    { a: "Paragraf deduktif", c: ["Gagasan pokok muncul lebih dulu", "Kalimat utama di awal paragraf"] },
    { a: "Paragraf induktif", c: ["Gagasan pokok muncul sebagai simpulan", "Kalimat utama di akhir paragraf"] },
    { a: "Kata baku", c: ["Contohnya apotek, ajek, antre", "Sesuai kaidah dan KBBI"] },
    { a: "Kata umum", c: ["Contohnya bunga, membawa, kendaraan", "Cakupan maknanya luas"] },
    { a: "Kata khusus", c: ["Contohnya mawar, menjinjing, becak", "Maknanya terbatas dan spesifik"] },
    { a: "Konjungsi antarkalimat", c: ["Contohnya Namun, Akhirnya, Oleh karena itu", "Ditulis di awal kalimat dan diikuti koma"] },
    { a: "Konjungsi intrakalimat", c: ["Ada yang didahului koma, ada yang tidak", "Menghubungkan klausa di dalam satu kalimat"] },
    { a: "Tanda baca penyingkat", c: ["Salah satunya berspasi di kedua sisi", "Elipsis dan apostrof"] },
    { a: "Tanda baca pengapit", c: ["Dipakai berpasangan", "Tanda petik, petik tunggal, kurung, kurung siku"] }] },
  { id: "t-manajemen", topic: "manajemen", title: "Tebak tokoh manajemen", pages: "134, 157-164", ask: "Siapa tokoh yang dimaksud?", items: [
    { a: "Max Weber", c: ["Hubungan antarpribadi bersifat impersonal", "Pembagian kerja dan hierarki wewenang", "Teori birokrasi"] },
    { a: "J.D. Mooney dan A. Reiley", c: ["Prinsip koordinasi, skalar, dan fungsional", "Teori administrasi"] },
    { a: "Hugo Munsterberg", c: ["Partisipasi dan manajemen bottom-up", "Teori neo-klasik"] },
    { a: "Abraham Maslow", c: ["Organisasi sebagai satu kesatuan yang saling bergantung", "Teori modern"] },
    { a: "George R. Terry", c: ["Fungsi actuating (pelaksanaan) pada bagan fungsi manajemen", "Perencanaan, pengorganisasian, penggerakan, pengawasan", "POAC"] },
    { a: "Henry Fayol", c: ["Enam kegiatan industri, dari teknikal sampai manajerial", "Fungsi commanding dan coordinating"] },
    { a: "Mintzberg", c: ["Peran antarpribadi, informasi, dan keputusan", "10 peran manajer dalam 3 kategori"] },
    { a: "Harold Koontz dan Cyril O'Donnell", c: ["Manajemen = pencapaian tujuan melalui dan dengan orang lain"] },
    { a: "John D. Millet", c: ["Manajemen = pembimbingan dan pemberian fasilitas bagi kelompok formal"] }] }
];
